/**
 * @file audio_stats.h
 * @brief Audio performance statistics tracking
 */

#ifndef AUDIO_STATS_H
#define AUDIO_STATS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Audio performance statistics structure
 */
typedef struct {
    /* Counters (reset each second) */
    uint32_t samples_generated;      /* Samples generated by APU */
    uint32_t samples_queued;         /* Samples written into the audio ring */
    uint32_t samples_dropped;        /* Samples dropped due to full ring */
    
    /* Current state */
    uint32_t buffer_fill_samples;    /* Current audio ring fill */
    uint32_t buffer_capacity_samples;/* Total audio ring capacity */
    uint32_t buffer_high_water_samples; /* Peak fill since reset */
    float buffer_latency_ms;         /* Estimated latency from ring fill */
    uint32_t device_sample_rate;     /* Active output sample rate */
    
    /* Timing */
    uint64_t last_reset_time_ms;     /* When counters were last reset */
    float sample_rate_actual;        /* Measured sample rate */
    
    /* Per-second snapshots (for display) */
    uint32_t last_samples_generated;
    uint32_t last_samples_queued;
    uint32_t last_samples_dropped;
    uint32_t last_buffer_underruns;
    
    /* Running totals */
    uint64_t total_samples_generated;
    uint64_t total_samples_queued;
    uint64_t total_samples_dropped;
    uint64_t total_buffer_underruns;
    
    /* Flags */
    bool enabled;
    bool log_to_console;
} AudioStats;

/* Global stats instance */
extern AudioStats g_audio_stats;

/**
 * Initialize audio statistics tracking
 */
void audio_stats_init(void);

/**
 * Reset per-second counters (call this once per second)
 */
void audio_stats_tick(uint64_t current_time_ms);

/**
 * Record a sample generation event
 */
static inline void audio_stats_sample_generated(void) {
    if (g_audio_stats.enabled) {
        g_audio_stats.samples_generated++;
        g_audio_stats.total_samples_generated++;
    }
}

/**
 * Record samples being queued to SDL
 */
static inline void audio_stats_samples_queued(uint32_t count) {
    if (g_audio_stats.enabled) {
        g_audio_stats.samples_queued += count;
        g_audio_stats.total_samples_queued += count;
    }
}

/**
 * Record samples being dropped
 */
static inline void audio_stats_samples_dropped(uint32_t count) {
    if (g_audio_stats.enabled) {
        g_audio_stats.samples_dropped += count;
        g_audio_stats.total_samples_dropped += count;
    }
}

/**
 * Update ring-buffer state from SDL
 */
void audio_stats_update_buffer(uint32_t fill_samples, uint32_t capacity_samples, uint32_t sample_rate);

/**
 * Record a buffer underrun (SDL ran out of data)
 */
static inline void audio_stats_underruns(uint32_t count) {
    if (g_audio_stats.enabled) {
        g_audio_stats.last_buffer_underruns += count;
        g_audio_stats.total_buffer_underruns += count;
    }
}

static inline void audio_stats_underrun(void) {
    audio_stats_underruns(1);
}

/**
 * Control whether audio stats are logged to the console each second.
 */
void audio_stats_set_log_to_console(bool enabled);

/**
 * Print current statistics to console
 */
void audio_stats_print(void);

/**
 * Get formatted statistics string for ImGui
 */
const char* audio_stats_get_summary(void);

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_STATS_H */
