/* Generated by gbrecomp */
#ifndef Resident_Evil_Gaiden__USA__H
#define Resident_Evil_Gaiden__USA__H

#include "gbrt.h"

const GBConfig* Resident_Evil_Gaiden__USA__default_config(void);
void Resident_Evil_Gaiden__USA__run(GBContext* ctx);
void Resident_Evil_Gaiden__USA__init(GBContext* ctx);
int Resident_Evil_Gaiden__USA__main(int argc, char* argv[]);

#endif
