/* Generated by gbrecomp from Resident Evil Gaiden (USA) */
#include "Resident_Evil_Gaiden__USA__internal.h"

/* Shared body at 07:401a */
static void body_07_401a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x401a: goto loc_07_401a;
        case 0x401b: goto loc_07_401b;
        case 0x401c: goto loc_07_401c;
        case 0x401d: goto loc_07_401d;
        case 0x401e: goto loc_07_401e;
        case 0x401f: goto loc_07_401f;
        case 0x4020: goto loc_07_4020;
        case 0x4021: goto loc_07_4021;
        case 0x4022: goto loc_07_4022;
        case 0x4023: goto pc_4023;
        case 0x4024: goto loc_07_4024;
        case 0x4025: goto pc_4025;
        case 0x4026: goto pc_4026;
        case 0x4027: goto loc_07_4027;
        case 0x4028: goto pc_4028;
        case 0x4029: goto pc_4029;
        case 0x402a: goto loc_07_402a;
        case 0x402b: goto pc_402b;
        case 0x402c: goto pc_402c;
        case 0x402d: goto pc_402d;
        case 0x402f: goto loc_07_402f;
        case 0x4030: goto pc_4030;
        case 0x4031: goto pc_4031;
        case 0x4032: goto pc_4032;
        case 0x4034: goto pc_4034;
        case 0x4035: goto pc_4035;
        case 0x4036: goto pc_4036;
        case 0x4037: goto pc_4037;
        case 0x4038: goto pc_4038;
        case 0x4039: goto pc_4039;
        case 0x403a: goto pc_403a;
        case 0x403b: goto pc_403b;
        case 0x403c: goto pc_403c;
        case 0x403e: goto loc_07_403e;
        case 0x403f: goto loc_07_403f;
        case 0x4040: goto loc_07_4040;
        case 0x4041: goto loc_07_4041;
        case 0x4042: goto loc_07_4042;
        case 0x4043: goto pc_4043;
        case 0x4044: goto loc_07_4044;
        case 0x4045: goto pc_4045;
        case 0x4046: goto pc_4046;
        case 0x4048: goto pc_4048;
        case 0x4049: goto pc_4049;
        case 0x404a: goto pc_404a;
        case 0x404b: goto pc_404b;
        case 0x404c: goto pc_404c;
        case 0x404d: goto pc_404d;
        case 0x404e: goto pc_404e;
        case 0x404f: goto pc_404f;
        case 0x4052: goto loc_07_4052;
        case 0x4053: goto pc_4053;
        case 0x4054: goto loc_07_4054;
        case 0x4055: goto pc_4055;
        case 0x4056: goto pc_4056;
        case 0x4057: goto pc_4057;
        case 0x4058: goto loc_07_4058;
        case 0x4059: goto loc_07_4059;
        case 0x405c: goto loc_07_405c;
        case 0x405d: goto pc_405d;
        case 0x405e: goto pc_405e;
        case 0x405f: goto pc_405f;
        case 0x4060: goto pc_4060;
        case 0x4061: goto loc_07_4061;
        case 0x4062: goto pc_4062;
        case 0x4063: goto pc_4063;
        case 0x4064: goto pc_4064;
        case 0x4065: goto pc_4065;
        case 0x4066: goto pc_4066;
        case 0x4067: goto pc_4067;
        case 0x406a: goto loc_07_406a;
        case 0x406b: goto pc_406b;
        case 0x406c: goto pc_406c;
        case 0x406d: goto pc_406d;
        case 0x406e: goto pc_406e;
        case 0x406f: goto pc_406f;
        case 0x4070: goto pc_4070;
        case 0x4071: goto pc_4071;
        case 0x4072: goto pc_4072;
        case 0x4073: goto pc_4073;
        case 0x4074: goto pc_4074;
        case 0x4075: goto pc_4075;
        case 0x4076: goto pc_4076;
        default: break;
    }

loc_07_3fdc:
    /* warning: fallthrough to unanalyzed code at 0x6c00 in bank 7 */
    return;
loc_07_401a:
    /* DEC C */
    /* 07:401a */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x401b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_401b:
    /* INC E */
    /* 07:401b */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x401c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_401c:
    /* LD B,$b7 */
    /* 07:401c */     ctx->b = 0xb7;
    ctx->pc = 0x401e;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_07_401e; /* fallthrough */
loc_07_401d:
    /* OR A */
    /* 07:401d */     gb_or8(ctx, ctx->a);
    ctx->pc = 0x401e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_401e:
    /* LD B,A */
    /* 07:401e */     ctx->b = ctx->a;
    ctx->pc = 0x401f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_401f:
    /* SBC A,$b3 */
    /* 07:401f */     gb_sbc8(ctx, 0xb3);
    ctx->pc = 0x4021;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_07_4021; /* fallthrough */
loc_07_4020:
    /* OR E */
    /* 07:4020 */     gb_or8(ctx, ctx->e);
    ctx->pc = 0x4021;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4021:
    /* LD (DE),A */
    /* 07:4021 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4022;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4022:
    /* LD C,L */
    /* 07:4022 */     ctx->c = ctx->l;
    ctx->pc = 0x4023;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET Z */
pc_4023:
    /* 07:4023 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4024, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4024:
    /* XOR H */
    /* 07:4024 */     gb_xor8(ctx, ctx->h);
    ctx->pc = 0x4025;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP E */
pc_4025:
    /* 07:4025 */     gb_cp8(ctx, ctx->e);
    ctx->pc = 0x4026;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,E */
pc_4026:
    /* 07:4026 */     gb_adc8(ctx, ctx->e);
    ctx->pc = 0x4027;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4027:
    /* AND (HL) */
    /* 07:4027 */     gb_tick(ctx, 7);
    gb_and8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x4028;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_4028:
    /* 07:4028 */     gb_rra(ctx);
    ctx->pc = 0x4029;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4029:
    /* 07:4029 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x402a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_402a:
    /* LD E,D */
    /* 07:402a */     ctx->e = ctx->d;
    ctx->pc = 0x402b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,L */
pc_402b:
    /* 07:402b */     ctx->a = ctx->l;
    ctx->pc = 0x402c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_402c:
    /* 07:402c */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x402d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR C,37 */
pc_402d:
    /* 07:402d */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0x4054, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_07_4054;
    } /* C */
    gbrt_timed_jump(ctx, 0x402f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_402f:
    /* RRA */
    /* 07:402f */     gb_rra(ctx);
    ctx->pc = 0x4030;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,L */
pc_4030:
    /* 07:4030 */     ctx->e = ctx->l;
    ctx->pc = 0x4031;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_4031:
    /* 07:4031 */     ctx->l = ctx->a;
    ctx->pc = 0x4032;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SET n,r */
pc_4032:
    /* 07:4032 */     ctx->h |= (1 << 7);
    ctx->pc = 0x4034;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB (HL) */
pc_4034:
    /* 07:4034 */     gb_tick(ctx, 7);
    gb_sub8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x4035;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_4035:
    /* 07:4035 */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x4036;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,L */
pc_4036:
    /* 07:4036 */     ctx->b = ctx->l;
    ctx->pc = 0x4037;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC SP */
pc_4037:
    /* 07:4037 */     gbrt_timed_dec16(ctx, &ctx->sp);
    ctx->pc = 0x4038;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_4038:
    /* 07:4038 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x4039;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(DE) */
pc_4039:
    /* 07:4039 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->de);
    gb_tick(ctx, 1);
    ctx->pc = 0x403a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,C */
pc_403a:
    /* 07:403a */     gb_adc8(ctx, ctx->c);
    ctx->pc = 0x403b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(BC) */
pc_403b:
    /* 07:403b */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->bc);
    gb_tick(ctx, 1);
    ctx->pc = 0x403c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_403c:
    /* 07:403c */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x403d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x403d in bank 7 */
    return;
loc_07_403e:
    /* XOR (HL) */
    /* 07:403e */     gb_tick(ctx, 7);
    gb_xor8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x403f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_403f:
    /* LD (HL-),A */
    /* 07:403f */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x4040;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4040:
    /* JR NZ,-102 */
    /* 07:4040 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x3fdc, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_07_3fdc;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4042, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_07_4042; /* fallthrough */
loc_07_4041:
    /* SBC A,D */
    /* 07:4041 */     gb_sbc8(ctx, ctx->d);
    ctx->pc = 0x4042;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4042:
    /* LD D,B */
    /* 07:4042 */     ctx->d = ctx->b;
    ctx->pc = 0x4043;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR $40 */
pc_4043:
    /* 07:4043 */     gb_xor8(ctx, 0x40);
    ctx->pc = 0x4045;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_4045:
    /* 07:4045 */     ctx->a = ctx->b;
    ctx->pc = 0x4046;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$fd */
pc_4046:
    /* 07:4046 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0xfd);
    gb_tick(ctx, 1);
    ctx->pc = 0x4048;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_4048:
    /* 07:4048 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4049;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,C */
pc_4049:
    /* 07:4049 */     ctx->c = ctx->c;
    ctx->pc = 0x404a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_404a:
    /* 07:404a */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x404b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_404b:
    /* 07:404b */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x404c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,(HL) */
pc_404c:
    /* 07:404c */     gb_tick(ctx, 7);
    gb_sbc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x404d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,L */
pc_404d:
    /* 07:404d */     ctx->a = ctx->l;
    ctx->pc = 0x404e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,C */
pc_404e:
    /* 07:404e */     ctx->c = ctx->c;
    ctx->pc = 0x404f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL C,$4fad */
pc_404f:
    /* 07:404f */     if (ctx->f_c) {
        gbrt_timed_call(ctx, 0x4fad, 0x4052);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_07_4fad(ctx);
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x4052, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_07_4052; /* fallthrough */
loc_07_4044:
    /* LD B,B */
    /* 07:4044 */     ctx->b = ctx->b;
    if (gbrt_test_breakpoint_enabled) {
        ctx->pc = 0x4045;
        ctx->stopped = 1;
        return;
    }
    ctx->pc = 0x4045;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
    /* 07:4045 */     ctx->a = ctx->b;
    ctx->pc = 0x4046;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$fd */
    /* 07:4046 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0xfd);
    gb_tick(ctx, 1);
    ctx->pc = 0x4048;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
    /* 07:4048 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4049;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,C */
    /* 07:4049 */     ctx->c = ctx->c;
    ctx->pc = 0x404a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
    /* 07:404a */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x404b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
    /* 07:404b */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x404c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,(HL) */
    /* 07:404c */     gb_tick(ctx, 7);
    gb_sbc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x404d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,L */
    /* 07:404d */     ctx->a = ctx->l;
    ctx->pc = 0x404e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,C */
    /* 07:404e */     ctx->c = ctx->c;
    ctx->pc = 0x404f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL C,$4fad */
    /* 07:404f */     if (ctx->f_c) {
        gbrt_timed_call(ctx, 0x4fad, 0x4052);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_07_4fad(ctx);
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x4052, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4052:
    /* INC D */
    /* 07:4052 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x4053;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,(C) */
pc_4053:
    /* 07:4053 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, GB_IO_BASE + ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x4054;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4054:
    /* LD B,H */
    /* 07:4054 */     ctx->b = ctx->h;
    ctx->pc = 0x4055;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,B */
pc_4055:
    /* 07:4055 */     ctx->b = ctx->b;
    if (gbrt_test_breakpoint_enabled) {
        ctx->pc = 0x4056;
        ctx->stopped = 1;
        return;
    }
    ctx->pc = 0x4056;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,(HL) */
pc_4056:
    /* 07:4056 */     gb_tick(ctx, 7);
    ctx->h = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4057;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NC */
pc_4057:
    /* 07:4057 */     if (!ctx->f_c) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x4058, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4058:
    /* LD L,E */
    /* 07:4058 */     ctx->l = ctx->e;
    ctx->pc = 0x4059;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4059:
    /* CALL NZ,$b730 */
    /* 07:4059 */     if (!ctx->f_z) {
        gbrt_timed_call(ctx, 0xb730, 0x405c);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x405c, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_405c:
    /* LD D,(HL) */
    /* 07:405c */     gb_tick(ctx, 7);
    ctx->d = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x405d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC SP */
pc_405d:
    /* 07:405d */     gbrt_timed_dec16(ctx, &ctx->sp);
    ctx->pc = 0x405e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND C */
pc_405e:
    /* 07:405e */     gb_and8(ctx, ctx->c);
    ctx->pc = 0x405f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_405f:
    /* 07:405f */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x4060;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR $22 */
pc_4060:
    /* 07:4060 */     gb_or8(ctx, 0x22);
    ctx->pc = 0x4062;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB C */
pc_4062:
    /* 07:4062 */     gb_sub8(ctx, ctx->c);
    ctx->pc = 0x4063;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,L */
pc_4063:
    /* 07:4063 */     gb_sbc8(ctx, ctx->l);
    ctx->pc = 0x4064;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,E */
pc_4064:
    /* 07:4064 */     ctx->c = ctx->e;
    ctx->pc = 0x4065;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,E */
pc_4065:
    /* 07:4065 */     gb_adc8(ctx, ctx->e);
    ctx->pc = 0x4066;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_4066:
    /* 07:4066 */     gb_rra(ctx);
    ctx->pc = 0x4067;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP C,$cab0 */
pc_4067:
    /* 07:4067 */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0xcab0, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x406a, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_07_406a; /* fallthrough */
loc_07_4061:
    /* LD (HL+),A */
    /* 07:4061 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x4062;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB C */
    /* 07:4062 */     gb_sub8(ctx, ctx->c);
    ctx->pc = 0x4063;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,L */
    /* 07:4063 */     gb_sbc8(ctx, ctx->l);
    ctx->pc = 0x4064;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,E */
    /* 07:4064 */     ctx->c = ctx->e;
    ctx->pc = 0x4065;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,E */
    /* 07:4065 */     gb_adc8(ctx, ctx->e);
    ctx->pc = 0x4066;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
    /* 07:4066 */     gb_rra(ctx);
    ctx->pc = 0x4067;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP C,$cab0 */
    /* 07:4067 */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0xcab0, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x406a, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_406a:
    /* SBC A,C */
    /* 07:406a */     gb_sbc8(ctx, ctx->c);
    ctx->pc = 0x406b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_406b:
    /* 07:406b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x406c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP C */
pc_406c:
    /* 07:406c */     gb_cp8(ctx, ctx->c);
    ctx->pc = 0x406d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_406d:
    /* 07:406d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x406e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,L */
pc_406e:
    /* 07:406e */     gb_sbc8(ctx, ctx->l);
    ctx->pc = 0x406f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,C */
pc_406f:
    /* 07:406f */     ctx->c = ctx->c;
    ctx->pc = 0x4070;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_4070:
    /* 07:4070 */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x4071;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_4071:
    /* 07:4071 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x4072;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_4072:
    /* 07:4072 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4073;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH BC */
pc_4073:
    /* 07:4073 */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x4074;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,C */
pc_4074:
    /* 07:4074 */     gb_sbc8(ctx, ctx->c);
    ctx->pc = 0x4075;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_4075:
    /* 07:4075 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x4076;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP HL */
pc_4076:
    /* 07:4076 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_07_401a(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_401b(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_401c(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_401d(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_401e(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_401f(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4020(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4021(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4022(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4027(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_402a(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_403e(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_403f(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4040(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4041(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4044(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4059(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_4061(GBContext* ctx) {
    body_07_401a(ctx);
}

void func_07_406a(GBContext* ctx) {
    body_07_401a(ctx);
}

/* Shared body at 07:4080 */
static void body_07_4080(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4080: goto loc_07_4080;
        case 0x4081: goto pc_4081;
        case 0x4082: goto pc_4082;
        case 0x4084: goto pc_4084;
        case 0x4085: goto pc_4085;
        case 0x4088: goto loc_07_4088;
        case 0x4089: goto pc_4089;
        default: break;
    }

loc_07_4080:
    /* CP A */
    /* 07:4080 */     gb_cp8(ctx, ctx->a);
    ctx->pc = 0x4081;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_4081:
    /* 07:4081 */     gb_rrca(ctx);
    ctx->pc = 0x4082;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB $2e */
pc_4082:
    /* 07:4082 */     gb_sub8(ctx, 0x2e);
    ctx->pc = 0x4084;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_4084:
    /* 07:4084 */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x4085;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL C,$668e */
pc_4085:
    /* 07:4085 */     if (ctx->f_c) {
        gbrt_timed_call(ctx, 0x668e, 0x4088);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_07_668e(ctx);
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x4088, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_4088:
    /* ADD A,E */
    /* 07:4088 */     gb_add8(ctx, ctx->e);
    ctx->pc = 0x4089;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $28 */
pc_4089:
    /* 07:4089 */     gbrt_timed_rst(ctx, 0x28, 0x408a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_28(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x408a in bank 7 */
    return;
}

void func_07_4080(GBContext* ctx) {
    body_07_4080(ctx);
}

/* Shared body at 07:4099 */
static void body_07_4099(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4099: goto loc_07_4099;
        case 0x409b: goto pc_409b;
        case 0x409d: goto pc_409d;
        case 0x409e: goto pc_409e;
        case 0x409f: goto pc_409f;
        case 0x40a0: goto pc_40a0;
        case 0x40a1: goto pc_40a1;
        default: break;
    }

loc_07_4099:
    /* AND $58 */
    /* 07:4099 */     gb_and8(ctx, 0x58);
    ctx->pc = 0x409b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$84) */
pc_409b:
    /* 07:409b */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_HRAM_BASE + 0x04);
    gb_tick(ctx, 1);
    ctx->pc = 0x409d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,A */
pc_409d:
    /* 07:409d */     ctx->c = ctx->a;
    ctx->pc = 0x409e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,D */
pc_409e:
    /* 07:409e */     ctx->c = ctx->d;
    ctx->pc = 0x409f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_409f:
    /* 07:409f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x40a0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_40a0:
    /* 07:40a0 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x40a1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $10 */
pc_40a1:
    /* 07:40a1 */     gbrt_timed_rst(ctx, 0x10, 0x40a2);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x40a2 in bank 7 */
    return;
}

void func_07_4099(GBContext* ctx) {
    body_07_4099(ctx);
}

/* Shared body at 07:40c2 */
static void body_07_40c2(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x40c2: goto loc_07_40c2;
        case 0x40c3: goto loc_07_40c3;
        case 0x40c4: goto pc_40c4;
        case 0x40c6: goto loc_07_40c6;
        case 0x40c7: goto pc_40c7;
        case 0x40c8: goto pc_40c8;
        case 0x40c9: goto pc_40c9;
        case 0x40ca: goto loc_07_40ca;
        default: break;
    }

loc_07_40c2:
    /* ADC A,A */
    /* 07:40c2 */     gb_adc8(ctx, ctx->a);
    ctx->pc = 0x40c3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_40c3:
    /* LD (HL),L */
    /* 07:40c3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x40c4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $58 */
pc_40c4:
    /* 07:40c4 */     gb_and8(ctx, 0x58);
    ctx->pc = 0x40c6;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_40c6:
    /* DEC E */
    /* 07:40c6 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x40c7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL+) */
pc_40c7:
    /* 07:40c7 */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x40c8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
pc_40c8:
    /* 07:40c8 */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x40c9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_40c9:
    /* 07:40c9 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x40ca, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_07_40ca:
    /* RST $30 */
    /* 07:40ca */     gbrt_timed_rst(ctx, 0x30, 0x40cb);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x40cb in bank 7 */
    return;
}

void func_07_40c2(GBContext* ctx) {
    body_07_40c2(ctx);
}

void func_07_40c3(GBContext* ctx) {
    body_07_40c2(ctx);
}

void func_07_40c6(GBContext* ctx) {
    body_07_40c2(ctx);
}

