/* Generated by gbrecomp from Resident Evil Gaiden (USA) */
#include "Resident_Evil_Gaiden__USA__internal.h"

/* Shared body at 31:607e */
static void body_31_607e(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x607e: goto loc_31_607e;
        case 0x607f: goto pc_607f;
        case 0x6080: goto pc_6080;
        case 0x6081: goto pc_6081;
        case 0x6082: goto pc_6082;
        case 0x6083: goto pc_6083;
        case 0x6084: goto pc_6084;
        case 0x6085: goto pc_6085;
        case 0x6086: goto pc_6086;
        case 0x6087: goto pc_6087;
        case 0x6088: goto pc_6088;
        case 0x6089: goto pc_6089;
        case 0x608a: goto pc_608a;
        case 0x608b: goto pc_608b;
        case 0x608c: goto pc_608c;
        default: break;
    }

loc_31_607e:
    /* RRCA */
    /* 31:607e */     gb_rrca(ctx);
    ctx->pc = 0x607f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,H */
pc_607f:
    /* 31:607f */     gb_sbc8(ctx, ctx->h);
    ctx->pc = 0x6080;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_6080:
    /* 31:6080 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x6081;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,L */
pc_6081:
    /* 31:6081 */     gb_sbc8(ctx, ctx->l);
    ctx->pc = 0x6082;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_6082:
    /* 31:6082 */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x6083;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,A */
pc_6083:
    /* 31:6083 */     gb_sbc8(ctx, ctx->a);
    ctx->pc = 0x6084;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND C */
pc_6084:
    /* 31:6084 */     gb_and8(ctx, ctx->c);
    ctx->pc = 0x6085;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6085:
    /* 31:6085 */     /* NOP */
    ctx->pc = 0x6086;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_6086:
    /* 31:6086 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x6087;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_6087:
    /* 31:6087 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x6088;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_6088:
    /* 31:6088 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x6089;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND E */
pc_6089:
    /* 31:6089 */     gb_and8(ctx, ctx->e);
    ctx->pc = 0x608a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND H */
pc_608a:
    /* 31:608a */     gb_and8(ctx, ctx->h);
    ctx->pc = 0x608b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR B */
pc_608b:
    /* 31:608b */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x608c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $08 */
pc_608c:
    /* 31:608c */     gbrt_timed_rst(ctx, 0x8, 0x608d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_08(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x608d in bank 49 */
    return;
}

void func_31_607e(GBContext* ctx) {
    body_31_607e(ctx);
}

/* Shared body at 31:608f */
static void body_31_608f(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x608f: goto loc_31_608f;
        case 0x6090: goto pc_6090;
        case 0x6091: goto pc_6091;
        case 0x6092: goto pc_6092;
        case 0x6093: goto pc_6093;
        case 0x6094: goto pc_6094;
        case 0x6095: goto pc_6095;
        case 0x6096: goto pc_6096;
        case 0x6097: goto pc_6097;
        case 0x6098: goto pc_6098;
        case 0x609b: goto loc_31_609b;
        case 0x609c: goto pc_609c;
        default: break;
    }

loc_31_608f:
    /* LD L,E */
    /* 31:608f */     ctx->l = ctx->e;
    ctx->pc = 0x6090;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR (HL) */
pc_6090:
    /* 31:6090 */     gb_tick(ctx, 7);
    gb_or8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x6091;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,E */
pc_6091:
    /* 31:6091 */     ctx->l = ctx->e;
    ctx->pc = 0x6092;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP B */
pc_6092:
    /* 31:6092 */     gb_cp8(ctx, ctx->b);
    ctx->pc = 0x6093;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,E */
pc_6093:
    /* 31:6093 */     ctx->l = ctx->e;
    ctx->pc = 0x6094;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_6094:
    /* 31:6094 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x6095;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_6095:
    /* 31:6095 */     /* NOP */
    ctx->pc = 0x6096;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP D */
pc_6096:
    /* 31:6096 */     gb_cp8(ctx, ctx->d);
    ctx->pc = 0x6097;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP C */
pc_6097:
    /* 31:6097 */     gb_cp8(ctx, ctx->c);
    ctx->pc = 0x6098;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NZ,$0433 */
pc_6098:
    /* 31:6098 */     if (!ctx->f_z) {
        gbrt_timed_call(ctx, 0x433, 0x609b);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_0433(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x609b, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_31_609b:
    /* LD A,A */
    /* 31:609b */     ctx->a = ctx->a;
    ctx->pc = 0x609c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_609c:
    /* 31:609c */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_31_608f(GBContext* ctx) {
    body_31_608f(ctx);
}

/* Shared body at 31:609e */
static void body_31_609e(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x609e: goto loc_31_609e;
        case 0x609f: goto loc_31_609f;
        case 0x60a0: goto pc_60a0;
        case 0x60a1: goto pc_60a1;
        case 0x60a2: goto pc_60a2;
        case 0x60a3: goto pc_60a3;
        case 0x60a4: goto pc_60a4;
        case 0x60a6: goto loc_31_60a6;
        case 0x60a7: goto loc_31_60a7;
        case 0x60a8: goto pc_60a8;
        case 0x60a9: goto pc_60a9;
        case 0x60aa: goto pc_60aa;
        case 0x60ab: goto pc_60ab;
        case 0x60ae: goto loc_31_60ae;
        case 0x60af: goto pc_60af;
        case 0x60b0: goto pc_60b0;
        case 0x60b1: goto pc_60b1;
        default: break;
    }

loc_31_609e:
    /* LD E,D */
    /* 31:609e */     ctx->e = ctx->d;
    ctx->pc = 0x609f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_31_609f:
    /* LD E,D */
    /* 31:609f */     ctx->e = ctx->d;
    ctx->pc = 0x60a0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,D */
pc_60a0:
    /* 31:60a0 */     ctx->e = ctx->d;
    ctx->pc = 0x60a1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_60a1:
    /* 31:60a1 */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x60a2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_60a2:
    /* 31:60a2 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x60a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_60a3:
    /* 31:60a3 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x60a4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $052d */
pc_60a4:
    /* 31:60a4 */     gbrt_timed_call(ctx, 0x52d, 0x60a7);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_052d(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_31_60a7; /* fallthrough */
loc_31_60a6:
    /* DEC B */
    /* 31:60a6 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x60a7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_31_60a7:
    /* DEC B */
    /* 31:60a7 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x60a8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_60a8:
    /* 31:60a8 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x60a9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,D */
pc_60a9:
    /* 31:60a9 */     ctx->d = ctx->d;
    ctx->pc = 0x60aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_60aa:
    /* 31:60aa */     ctx->d = ctx->h;
    ctx->pc = 0x60ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL C,$dcd3 */
pc_60ab:
    /* 31:60ab */     if (ctx->f_c) {
        gbrt_timed_call(ctx, 0xdcd3, 0x60ae);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x60ae, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_31_60ae:
    /* DEC L */
    /* 31:60ae */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x60af;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_60af:
    /* 31:60af */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x60b0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_60b0:
    /* 31:60b0 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x60b1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $10 */
pc_60b1:
    /* 31:60b1 */     gbrt_timed_rst(ctx, 0x10, 0x60b2);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x60b2 in bank 49 */
    return;
}

void func_31_609e(GBContext* ctx) {
    body_31_609e(ctx);
}

void func_31_609f(GBContext* ctx) {
    body_31_609e(ctx);
}

void func_31_60a6(GBContext* ctx) {
    body_31_609e(ctx);
}

/* Shared body at 31:60c9 */
static void body_31_60c9(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x60c9: goto loc_31_60c9;
        case 0x60ca: goto pc_60ca;
        case 0x60cb: goto pc_60cb;
        case 0x60cc: goto pc_60cc;
        case 0x60cd: goto loc_31_60cd;
        case 0x60ce: goto loc_31_60ce;
        case 0x60cf: goto pc_60cf;
        case 0x60d0: goto loc_31_60d0;
        default: break;
    }

loc_31_60c9:
    /* CP D */
    /* 31:60c9 */     gb_cp8(ctx, ctx->d);
    ctx->pc = 0x60ca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP D */
pc_60ca:
    /* 31:60ca */     gb_cp8(ctx, ctx->d);
    ctx->pc = 0x60cb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,E */
pc_60cb:
    /* 31:60cb */     gb_adc8(ctx, ctx->e);
    ctx->pc = 0x60cc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_60cc:
    /* 31:60cc */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x60cd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_31_60cd:
    /* LD A,($d77f) */
    /* 31:60cd */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAMX_BASE + 0x077f);
    gb_tick(ctx, 1);
    ctx->pc = 0x60d0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_31_60d0; /* fallthrough */
loc_31_60ce:
    /* LD A,A */
    /* 31:60ce */     ctx->a = ctx->a;
    ctx->pc = 0x60cf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $10 */
pc_60cf:
    /* 31:60cf */     gbrt_timed_rst(ctx, 0x10, 0x60d0);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_31_60d0:
    /* RST $18 */
    /* 31:60d0 */     gbrt_timed_rst(ctx, 0x18, 0x60d1);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_18(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x60d1 in bank 49 */
    return;
}

void func_31_60c9(GBContext* ctx) {
    body_31_60c9(ctx);
}

void func_31_60cd(GBContext* ctx) {
    body_31_60c9(ctx);
}

void func_31_60ce(GBContext* ctx) {
    body_31_60c9(ctx);
}

void func_31_60d0(GBContext* ctx) {
    body_31_60c9(ctx);
}

