/* Generated by gbrecomp from Resident Evil Gaiden (USA) */
#include "Resident_Evil_Gaiden__USA__internal.h"

/* Shared body at 0000 */
static void body_0000(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0000:
    /* RETI */
    /* 0000 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_0001(ctx);
    return;
}

void rst_00(GBContext* ctx) {
    body_0000(ctx);
}

/* Shared body at 0001 */
static void body_0001(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0001: goto loc_0001;
        case 0x0002: goto loc_0002;
        case 0x0003: goto loc_0003;
        case 0x0004: goto loc_0004;
        case 0x0005: goto loc_0005;
        case 0x0006: goto loc_0006;
        default: break;
    }

loc_0001:
    /* RST $38 */
    /* 0001 */     gbrt_timed_rst(ctx, 0x38, 0x2);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0002:
    /* RST $38 */
    /* 0002 */     gbrt_timed_rst(ctx, 0x38, 0x3);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0003:
    /* RST $38 */
    /* 0003 */     gbrt_timed_rst(ctx, 0x38, 0x4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0004:
    /* RST $38 */
    /* 0004 */     gbrt_timed_rst(ctx, 0x38, 0x5);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0005:
    /* RST $38 */
    /* 0005 */     gbrt_timed_rst(ctx, 0x38, 0x6);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0006:
    /* RST $38 */
    /* 0006 */     gbrt_timed_rst(ctx, 0x38, 0x7);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7 in bank 0 */
    return;
}

void func_0001(GBContext* ctx) {
    body_0001(ctx);
}

void func_0002(GBContext* ctx) {
    body_0001(ctx);
}

void func_0003(GBContext* ctx) {
    body_0001(ctx);
}

void func_0004(GBContext* ctx) {
    body_0001(ctx);
}

void func_0006(GBContext* ctx) {
    body_0001(ctx);
}

/* Shared body at 0008 */
static void body_0008(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0008: goto loc_0008;
        case 0x0009: goto loc_0009;
        case 0x000a: goto loc_000a;
        default: break;
    }

loc_0008:
    /* RST $38 */
    /* 0008 */     gbrt_timed_rst(ctx, 0x38, 0x9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0009:
    /* RST $38 */
    /* 0009 */     gbrt_timed_rst(ctx, 0x38, 0xa);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_000a:
    /* RST $38 */
    /* 000a */     gbrt_timed_rst(ctx, 0x38, 0xb);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0xb in bank 0 */
    return;
}

void rst_08(GBContext* ctx) {
    body_0008(ctx);
}

void func_0009(GBContext* ctx) {
    body_0008(ctx);
}

/* Shared body at 000c */
static void body_000c(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x000c: goto loc_000c;
        case 0x000d: goto loc_000d;
        case 0x000e: goto loc_000e;
        case 0x000f: goto loc_000f;
        default: break;
    }

loc_000c:
    /* RST $38 */
    /* 000c */     gbrt_timed_rst(ctx, 0x38, 0xd);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_000d:
    /* RST $38 */
    /* 000d */     gbrt_timed_rst(ctx, 0x38, 0xe);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_000e:
    /* RST $38 */
    /* 000e */     gbrt_timed_rst(ctx, 0x38, 0xf);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_000f:
    /* RST $38 */
    /* 000f */     gbrt_timed_rst(ctx, 0x38, 0x10);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x10 in bank 0 */
    return;
}

void func_000c(GBContext* ctx) {
    body_000c(ctx);
}

void func_000d(GBContext* ctx) {
    body_000c(ctx);
}

void func_000e(GBContext* ctx) {
    body_000c(ctx);
}

void func_000f(GBContext* ctx) {
    body_000c(ctx);
}

/* Shared body at 0013 */
static void body_0013(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0013: goto loc_0013;
        case 0x0014: goto loc_0014;
        default: break;
    }

loc_0013:
    /* RST $38 */
    /* 0013 */     gbrt_timed_rst(ctx, 0x38, 0x14);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0014:
    /* RST $38 */
    /* 0014 */     gbrt_timed_rst(ctx, 0x38, 0x15);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x15 in bank 0 */
    return;
}

void func_0013(GBContext* ctx) {
    body_0013(ctx);
}

void func_0014(GBContext* ctx) {
    body_0013(ctx);
}

/* Shared body at 0016 */
static void body_0016(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0016:
    /* RST $38 */
    /* 0016 */     gbrt_timed_rst(ctx, 0x38, 0x17);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x17 in bank 0 */
    return;
}

void func_0016(GBContext* ctx) {
    body_0016(ctx);
}

/* Shared body at 0018 */
static void body_0018(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0018: goto loc_0018;
        case 0x0019: goto loc_0019;
        default: break;
    }

loc_0018:
    /* RST $38 */
    /* 0018 */     gbrt_timed_rst(ctx, 0x38, 0x19);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0019:
    /* RST $38 */
    /* 0019 */     gbrt_timed_rst(ctx, 0x38, 0x1a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x1a in bank 0 */
    return;
}

void rst_18(GBContext* ctx) {
    body_0018(ctx);
}

void func_0019(GBContext* ctx) {
    body_0018(ctx);
}

/* Shared body at 0020 */
static void body_0020(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0020: goto loc_0020;
        case 0x0021: goto loc_0021;
        default: break;
    }

loc_0020:
    /* RST $38 */
    /* 0020 */     gbrt_timed_rst(ctx, 0x38, 0x21);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0021:
    /* RST $38 */
    /* 0021 */     gbrt_timed_rst(ctx, 0x38, 0x22);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x22 in bank 0 */
    return;
}

void rst_20(GBContext* ctx) {
    body_0020(ctx);
}

void func_0021(GBContext* ctx) {
    body_0020(ctx);
}

/* Shared body at 0026 */
static void body_0026(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0026:
    /* RST $38 */
    /* 0026 */     gbrt_timed_rst(ctx, 0x38, 0x27);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x27 in bank 0 */
    return;
}

void func_0026(GBContext* ctx) {
    body_0026(ctx);
}

/* Shared body at 0028 */
static void body_0028(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0028:
    /* RST $38 */
    /* 0028 */     gbrt_timed_rst(ctx, 0x38, 0x29);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x29 in bank 0 */
    return;
}

void rst_28(GBContext* ctx) {
    body_0028(ctx);
}

/* Shared body at 002a */
static void body_002a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x002a: goto loc_002a;
        case 0x002b: goto loc_002b;
        default: break;
    }

loc_002a:
    /* RST $38 */
    /* 002a */     gbrt_timed_rst(ctx, 0x38, 0x2b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_002b:
    /* RST $38 */
    /* 002b */     gbrt_timed_rst(ctx, 0x38, 0x2c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x2c in bank 0 */
    return;
}

void func_002a(GBContext* ctx) {
    body_002a(ctx);
}

void func_002b(GBContext* ctx) {
    body_002a(ctx);
}

/* Shared body at 002d */
static void body_002d(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x002d: goto loc_002d;
        case 0x002e: goto loc_002e;
        default: break;
    }

loc_002d:
    /* RST $38 */
    /* 002d */     gbrt_timed_rst(ctx, 0x38, 0x2e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_002e:
    /* RST $38 */
    /* 002e */     gbrt_timed_rst(ctx, 0x38, 0x2f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x2f in bank 0 */
    return;
}

void func_002d(GBContext* ctx) {
    body_002d(ctx);
}

void func_002e(GBContext* ctx) {
    body_002d(ctx);
}

/* Shared body at 0030 */
static void body_0030(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0030:
    /* RST $38 */
    /* 0030 */     gbrt_timed_rst(ctx, 0x38, 0x31);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x31 in bank 0 */
    return;
}

void rst_30(GBContext* ctx) {
    body_0030(ctx);
}

/* Shared body at 0032 */
static void body_0032(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0032:
    /* RST $38 */
    /* 0032 */     gbrt_timed_rst(ctx, 0x38, 0x33);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x33 in bank 0 */
    return;
}

void func_0032(GBContext* ctx) {
    body_0032(ctx);
}

/* Shared body at 0037 */
static void body_0037(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0036: goto loc_0036;
        case 0x0037: goto loc_0037;
        case 0x3a04: goto loc_3a04;
        case 0x3a05: goto loc_3a05;
        case 0x3a06: goto loc_3a06;
        case 0x3a07: goto loc_3a07;
        case 0x3a08: goto loc_3a08;
        case 0x3a09: goto loc_3a09;
        default: break;
    }

loc_0036:
    /* RST $38 */
    /* 0036 */     gbrt_timed_rst(ctx, 0x38, 0x37);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_0037:
    /* RST $38 */
    /* 0037 */     gbrt_timed_rst(ctx, 0x38, 0x38);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x38 in bank 0 */
    return;
loc_3a04:
    /* LD HL,$c2e1 */
    /* 3a04 */     ctx->hl = GB_WRAM0_BASE + 0x02e1;
    ctx->pc = 0x3a07;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_3a07; /* fallthrough */
loc_3a05:
    /* POP HL */
    /* 3a05 */     ctx->hl = gbrt_timed_pop16(ctx);
    ctx->pc = 0x3a06;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_3a06:
    /* JP NZ,$0036 */
    /* 3a06 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x36, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_0036;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x3a09, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_3a09; /* fallthrough */
loc_3a07:
    /* LD (HL),$00 */
    /* 3a07 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x3a09;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_3a09; /* fallthrough */
loc_3a08:
    /* NOP */
    /* 3a08 */     /* NOP */
    ctx->pc = 0x3a09;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_3a09:
    /* RET */
    /* 3a09 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_0037(GBContext* ctx) {
    body_0037(ctx);
}

void func_3a04(GBContext* ctx) {
    body_0037(ctx);
}

void func_3a05(GBContext* ctx) {
    body_0037(ctx);
}

void func_3a06(GBContext* ctx) {
    body_0037(ctx);
}

void func_3a07(GBContext* ctx) {
    body_0037(ctx);
}

void func_3a08(GBContext* ctx) {
    body_0037(ctx);
}

void func_3a09(GBContext* ctx) {
    body_0037(ctx);
}

/* Shared body at 0039 */
static void body_0039(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x0039: goto loc_0039;
        case 0x003a: goto loc_003a;
        case 0x003b: goto loc_003b;
        case 0x003c: goto loc_003c;
        case 0x003d: goto loc_003d;
        default: break;
    }

loc_0039:
    /* RST $38 */
    /* 0039 */     gbrt_timed_rst(ctx, 0x38, 0x3a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_003a:
    /* RST $38 */
    /* 003a */     gbrt_timed_rst(ctx, 0x38, 0x3b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_003b:
    /* RST $38 */
    /* 003b */     gbrt_timed_rst(ctx, 0x38, 0x3c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_003c:
    /* RST $38 */
    /* 003c */     gbrt_timed_rst(ctx, 0x38, 0x3d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
loc_003d:
    /* RST $38 */
    /* 003d */     gbrt_timed_rst(ctx, 0x38, 0x3e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* Fallback to dispatcher */
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x3e in bank 0 */
    return;
}

void func_0039(GBContext* ctx) {
    body_0039(ctx);
}

void func_003a(GBContext* ctx) {
    body_0039(ctx);
}

void func_003b(GBContext* ctx) {
    body_0039(ctx);
}

